from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
import threading
from typing import Any, Dict, Iterator, List, Optional, Union
import uuid

from backend.runtime.event import Event, EventBus, EventType
from backend.runtime.exceptions import NexusException
from backend.runtime.logger import StructuredLogger


class ModelError(NexusException):
    """Base exception for all model interface related errors."""
    pass


class ModelValidationError(ModelError):
    """Raised when request properties, capabilities, or registrations are invalid."""
    pass


class ProviderNotFoundError(ModelError):
    """Raised when the specified provider is not registered."""
    pass


class ModelNotFoundError(ModelError):
    """Raised when the specified model cannot be found in registries."""
    pass


class UnsupportedCapabilityError(ModelError):
    """Raised when a model is requested to perform an unsupported task capability."""
    pass


class ModelCapability(Enum):
    """Classifications of capabilities provided by models."""
    CHAT = "CHAT"
    COMPLETION = "COMPLETION"
    EMBEDDING = "EMBEDDING"
    IMAGE = "IMAGE"
    AUDIO = "AUDIO"
    VIDEO = "VIDEO"
    FUNCTION_CALLING = "FUNCTION_CALLING"
    STREAMING = "STREAMING"
    STRUCTURED_OUTPUT = "STRUCTURED_OUTPUT"
    MULTIMODAL = "MULTIMODAL"


@dataclass(frozen=True)
class ModelInfo:
    """Immutable model describing model capabilities, scope, and boundaries.

    Attributes:
        model_id: Unique string identifier for the model.
        provider: Provider identifier associated with this model.
        name: Common name of the model.
        version: Version identifier.
        context_window: Max input tokens allowed.
        max_output_tokens: Max output tokens generation limit.
        supported_modalities: List of modalities (e.g. text, image).
        capabilities: Extended capabilities interfaces.
        metadata: Extra metadata details.
    """
    model_id: str
    provider: str
    name: str
    version: str
    context_window: int
    max_output_tokens: int
    supported_modalities: List[str]
    capabilities: List[ModelCapability]
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class InferenceRequest:
    """Encapsulates inference parameters for model completion generation.

    Attributes:
        model: Target model ID.
        messages: Chat messages history list.
        prompt: Optional raw string query prompt.
        parameters: Generation parameters temperature, top_p, etc.
        tools: Declared schema of tools/functions callable by the model.
        response_format: Constraints schemas for structured generation formats.
        metadata: Extra metadata payload.
    """
    model: str
    messages: List[Dict[str, Any]] = field(default_factory=list)
    prompt: Optional[str] = None
    parameters: Dict[str, Any] = field(default_factory=dict)
    tools: List[Dict[str, Any]] = field(default_factory=list)
    response_format: Optional[Dict[str, Any]] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class InferenceResponse:
    """Immutable outcome descriptor of model generation requests.

    Attributes:
        request_id: Unique UUID tracking request transaction.
        content: Textual content generated by the model.
        finish_reason: Termination reason (e.g. stop, length, content_filter).
        token_usage: Metadata dictionary specifying prompt/completion token usage.
        latency: Time taken in seconds.
        provider: Provider identifier.
        model: Model identifier.
        metadata: Extra metadata details.
    """
    request_id: str
    content: str
    finish_reason: str
    token_usage: Dict[str, int]
    latency: float
    provider: str
    model: str
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class EmbeddingRequest:
    """Parameters query descriptor for model vector embed generation.

    Attributes:
        model: Target model ID.
        input: Text string or list of text strings to embed.
        parameters: Target backend specific variables.
        metadata: Extra metadata payload.
    """
    model: str
    input: Union[str, List[str]]
    parameters: Dict[str, Any] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class EmbeddingResponse:
    """Vector representation response payload from embedding providers.

    Attributes:
        request_id: Unique UUID tracking embedding request.
        embeddings: List of list of float values representing dimensions.
        token_usage: Metadata details tracking token consumption.
        latency: Time taken in seconds.
        provider: Provider identifier.
        model: Model identifier.
        metadata: Extra metadata details.
    """
    request_id: str
    embeddings: List[List[float]]
    token_usage: Dict[str, int]
    latency: float
    provider: str
    model: str
    metadata: Dict[str, Any] = field(default_factory=dict)


class ModelProvider(ABC):
    """Abstract Base Class defining standard capability interfaces for LLM adapters."""

    @abstractmethod
    def generate(self, request: InferenceRequest) -> InferenceResponse:
        """Processes completion inference request.

        Args:
            request: Inference request details.

        Returns:
            InferenceResponse: Response model context.
        """
        pass

    @abstractmethod
    def generate_stream(self, request: InferenceRequest) -> Iterator[InferenceResponse]:
        """Processes completion stream generation.

        Args:
            request: Inference request details.

        Returns:
            Iterator[InferenceResponse]: Generator yielding chunks of responses.
        """
        pass

    @abstractmethod
    def embed(self, request: EmbeddingRequest) -> EmbeddingResponse:
        """Processes request to generate dimensional embeddings.

        Args:
            request: Embed request details.

        Returns:
            EmbeddingResponse: Response model embeddings.
        """
        pass

    @abstractmethod
    def list_models(self) -> List[ModelInfo]:
        """Lists description details of models supported by the provider.

        Returns:
            List[ModelInfo]: Supported models catalog.
        """
        pass

    @abstractmethod
    def get_model(self, model_id: str) -> ModelInfo:
        """Retrieves details of specified model.

        Args:
            model_id: Target model ID.

        Returns:
            ModelInfo: Match details.
        """
        pass

    @abstractmethod
    def health_check(self) -> bool:
        """Queries provider endpoint connection state.

        Returns:
            bool: True if healthy and accessible.
        """
        pass

    @abstractmethod
    def supports(self, capability: ModelCapability) -> bool:
        """Checks if capability is supported generally.

        Args:
            capability: Request capability.

        Returns:
            bool: True if supported.
        """
        pass


class ModelRegistry:
    """Thread-safe Singleton registry mapping and routing to ModelProviders."""
    _instance: Optional["ModelRegistry"] = None
    _singleton_lock: threading.Lock = threading.Lock()

    def __new__(cls, *args: Any, **kwargs: Any) -> "ModelRegistry":
        if not cls._instance:
            with cls._singleton_lock:
                if not cls._instance:
                    cls._instance = super().__new__(cls)
                    cls._instance._initialized = False
        return cls._instance

    def __init__(self) -> None:
        if getattr(self, "_initialized", False):
            return
        with self._singleton_lock:
            if getattr(self, "_initialized", False):
                return
            self.logger = StructuredLogger()
            self.event_bus = EventBus()
            self._providers: Dict[str, ModelProvider] = {}
            self._lock: threading.RLock = threading.RLock()
            self._initialized = True

    def register_provider(self, provider_id: str, provider: ModelProvider) -> None:
        """Registers a ModelProvider.

        Args:
            provider_id: Unique string key identifier.
            provider: Active class interface instance.

        Raises:
            ModelValidationError: On duplicate registrations or verification fails.
        """
        if not provider_id or not str(provider_id).strip():
            raise ModelValidationError("provider_id cannot be empty.")
        if not provider:
            raise ModelValidationError("provider instance cannot be None.")

        self.logger.info(f"Model provider registration started for: {provider_id}")

        with self._lock:
            if provider_id in self._providers:
                raise ModelValidationError(f"Provider '{provider_id}' is already registered.")

            # Validate duplicate model IDs across all providers
            new_models = provider.list_models()
            for new_model in new_models:
                for pid, reg_prov in self._providers.items():
                    for existing_model in reg_prov.list_models():
                        if existing_model.model_id == new_model.model_id:
                            raise ModelValidationError(
                                f"Model ID '{new_model.model_id}' is already registered under provider '{pid}'."
                            )

            self._providers[provider_id] = provider

        self._publish_event("model.provider.registered", provider_id=provider_id)
        self.logger.info(f"Successful model provider registration. ID: {provider_id}")

    def unregister_provider(self, provider_id: str) -> None:
        """Removes a provider from the active registry.

        Args:
            provider_id: Unique provider ID.

        Raises:
            ProviderNotFoundError: If provider ID doesn't exist.
        """
        self.logger.info(f"Model provider unregistration started for: {provider_id}")

        with self._lock:
            if provider_id not in self._providers:
                raise ProviderNotFoundError(f"Provider '{provider_id}' is not registered.")
            del self._providers[provider_id]

        self._publish_event("model.provider.removed", provider_id=provider_id)
        self.logger.info(f"Successful provider unregistration. ID: {provider_id}")

    def get_provider(self, provider_id: str) -> ModelProvider:
        """Retrieves a registered ModelProvider instance.

        Args:
            provider_id: Unique provider ID.

        Returns:
            ModelProvider: Active provider class.

        Raises:
            ProviderNotFoundError: If provider ID is missing.
        """
        with self._lock:
            if provider_id not in self._providers:
                raise ProviderNotFoundError(f"Provider '{provider_id}' is not registered.")
            return self._providers[provider_id]

    def get_model(self, model_id: str) -> ModelInfo:
        """Searches model catalogs across all registered providers to find ModelInfo details.

        Args:
            model_id: Target model ID.

        Returns:
            ModelInfo: Match details.

        Raises:
            ModelNotFoundError: If model catalog mapping fails.
        """
        with self._lock:
            for provider in self._providers.values():
                for model in provider.list_models():
                    if model.model_id == model_id:
                        return model
            raise ModelNotFoundError(f"Model '{model_id}' not found in any registered provider catalog.")

    def get_provider_for_model(self, model_id: str) -> ModelProvider:
        """Gets provider associated with model."""
        with self._lock:
            for provider in self._providers.values():
                for model in provider.list_models():
                    if model.model_id == model_id:
                        return provider
            raise ModelNotFoundError(f"Model '{model_id}' has no registered provider.")

    def list_models(self) -> List[ModelInfo]:
        """Gathers catalog models details across all registered providers.

        Returns:
            List[ModelInfo]: Gathers catalogs models list.
        """
        models_list = []
        with self._lock:
            for provider in self._providers.values():
                models_list.extend(provider.list_models())
        return models_list

    def list_providers(self) -> List[str]:
        """Lists IDs of registered providers.

        Returns:
            List[str]: List of provider IDs.
        """
        with self._lock:
            return list(self._providers.keys())

    def find_by_capability(self, capability: ModelCapability) -> List[ModelInfo]:
        """Finds all models supporting specified capability.

        Args:
            capability: Target capability classification.

        Returns:
            List[ModelInfo]: Matching models list.
        """
        matched = []
        with self._lock:
            for provider in self._providers.values():
                for model in provider.list_models():
                    if capability in model.capabilities:
                        matched.append(model)
        return matched

    def health_check(self) -> Dict[str, bool]:
        """Executes connection check test hooks on all active registered providers.

        Returns:
            Dict[str, bool]: Key-value status checks dictionary.
        """
        status_map = {}
        with self._lock:
            for pid, provider in self._providers.items():
                try:
                    status_map[pid] = provider.health_check()
                except Exception:
                    status_map[pid] = False
        return status_map

    def generate(self, request: InferenceRequest) -> InferenceResponse:
        """Routes generate request.

        Args:
            request: Inference request details.

        Returns:
            InferenceResponse: Response model context.
        """
        if not request or not request.model:
            raise ModelValidationError("InferenceRequest must specify a valid model.")

        provider = self.get_provider_for_model(request.model)
        model_info = self.get_model(request.model)

        # Validate capability CHAT / COMPLETION support
        required_cap = ModelCapability.CHAT if request.messages else ModelCapability.COMPLETION
        if required_cap not in model_info.capabilities:
            raise UnsupportedCapabilityError(f"Model '{request.model}' does not support '{required_cap.value}' capability.")

        req_id = str(uuid.uuid4())
        self._publish_event("model.request.started", request_id=req_id, model=request.model)

        try:
            response = provider.generate(request)
            self._publish_event("model.request.completed", request_id=req_id, model=request.model)
            return response
        except Exception as e:
            self._publish_event("model.request.failed", request_id=req_id, model=request.model, error=str(e))
            raise ModelError(f"Inference request execution failed: {e}") from e

    def embed(self, request: EmbeddingRequest) -> EmbeddingResponse:
        """Routes embed request.

        Args:
            request: Embedding request details.

        Returns:
            EmbeddingResponse: Response model embeddings.
        """
        if not request or not request.model:
            raise ModelValidationError("EmbeddingRequest must specify a valid model.")

        provider = self.get_provider_for_model(request.model)
        model_info = self.get_model(request.model)

        if ModelCapability.EMBEDDING not in model_info.capabilities:
            raise UnsupportedCapabilityError(f"Model '{request.model}' does not support '{ModelCapability.EMBEDDING.value}' capability.")

        req_id = str(uuid.uuid4())
        self._publish_event("model.request.started", request_id=req_id, model=request.model)

        try:
            response = provider.embed(request)
            self._publish_event("model.request.completed", request_id=req_id, model=request.model)
            return response
        except Exception as e:
            self._publish_event("model.request.failed", request_id=req_id, model=request.model, error=str(e))
            raise ModelError(f"Embedding request execution failed: {e}") from e

    def _publish_event(self, event_name: str, **kwargs: Any) -> None:
        event = Event(
            event_type=EventType.CUSTOM_EVENT,
            source="ModelInterface",
            payload={"event_name": event_name, **kwargs}
        )
        self.event_bus.publish(event)
