from abc import ABC, abstractmethod
import concurrent.futures
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
import threading
import time
from typing import Any, Dict, List, Optional, Union
import uuid

from backend.runtime.base import AgentState, AgentStatus, BaseAgent
from backend.runtime.event import Event, EventBus, EventType
from backend.runtime.exceptions import NexusException
from backend.runtime.logger import StructuredLogger
from backend.runtime.task import Task


class OrchestratorError(NexusException):
    """Base exception for all Orchestrator Agent related errors."""
    pass


class AgentValidationError(OrchestratorError):
    """Raised when registering invalid agents or when capability matching fails."""
    pass


class OrchestrationPlanError(OrchestratorError):
    """Raised when plan generation, validation, or execution fails."""
    pass


class AgentCapability(Enum):
    """Logical capability types defining specialties supported by framework agents."""
    CHAT = "CHAT"
    OCR = "OCR"
    SEARCH = "SEARCH"
    EMBEDDING = "EMBEDDING"
    DOCUMENT_PROCESSING = "DOCUMENT_PROCESSING"
    CODE_ANALYSIS = "CODE_ANALYSIS"
    RESUME_ANALYSIS = "RESUME_ANALYSIS"
    MEETING_ANALYSIS = "MEETING_ANALYSIS"
    ANALYTICS = "ANALYTICS"
    BILLING = "BILLING"
    CUSTOM = "CUSTOM"


@dataclass(frozen=True)
class AgentRequest:
    """Immutable model encapsulating user query inputs for the orchestrator.

    Attributes:
        request_id: Unique string tracking request.
        user_id: Unique user identifier.
        input: Text string input.
        context: Context parameters dict.
        priority: Priority level.
        metadata: Extra options mapping.
        created_at: Datetime stamp.
    """
    request_id: str
    user_id: str
    input: str
    context: Dict[str, Any] = field(default_factory=dict)
    priority: str = "NORMAL"
    metadata: Dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class AgentResponse:
    """Outcome payload generated by orchestrator execution.

    Attributes:
        response_id: Unique response ID.
        request_id: Matching request ID.
        outputs: Dictionary mapping agent IDs or names to execution results.
        execution_summary: Explanatory summary text.
        metrics: Dictionary mapping execution latency and statistics.
        status: Status code ("SUCCESS" or "FAILURE").
    """
    response_id: str
    request_id: str
    outputs: Dict[str, Any]
    execution_summary: str
    metrics: Dict[str, Any]
    status: str


@dataclass(frozen=True)
class OrchestrationExecutionPlan:
    """Defines coordinating sequence and group topologies for agent dispatch.

    Attributes:
        plan_id: Unique plan ID.
        participating_agents: List of agent IDs needed.
        dependencies: Dictionary mapping agent IDs to dependency list.
        execution_order: Topological order of execution list.
        parallel_groups: List of lists indicating execution groups.
        fallback_strategy: Strategy name on agent crashes.
    """
    plan_id: str
    participating_agents: List[str]
    dependencies: Dict[str, List[str]]
    execution_order: List[str]
    parallel_groups: List[List[str]]
    fallback_strategy: str = "abort"  # abort, ignore, retry


class AgentRegistry:
    """Thread-safe Singleton registry dedicated to agent discovery."""
    _instance: Optional["AgentRegistry"] = None
    _singleton_lock: threading.Lock = threading.Lock()

    def __new__(cls, *args: Any, **kwargs: Any) -> "AgentRegistry":
        if not cls._instance:
            with cls._singleton_lock:
                if not cls._instance:
                    cls._instance = super().__new__(cls)
                    cls._instance._initialized = False
        return cls._instance

    def __init__(self) -> None:
        if getattr(self, "_initialized", False):
            return
        with self._singleton_lock:
            if getattr(self, "_initialized", False):
                return
            self.logger = StructuredLogger()
            self._agents: Dict[str, BaseAgent] = {}
            self._lock = threading.RLock()
            self._initialized = True

    def register_agent(self, agent_id: str, agent: BaseAgent) -> None:
        """Registers a BaseAgent.

        Args:
            agent_id: Unique string identifier.
            agent: Active agent instance.

        Raises:
            AgentValidationError: On duplicate IDs or invalid parameters.
        """
        if not agent_id or not str(agent_id).strip():
            raise AgentValidationError("agent_id cannot be empty.")
        if not agent:
            raise AgentValidationError("agent instance cannot be None.")

        with self._lock:
            if agent_id in self._agents:
                raise AgentValidationError(f"Agent '{agent_id}' is already registered.")
            self._agents[agent_id] = agent

        self.logger.info(f"Agent registered in registry. ID: {agent_id}")

    def unregister_agent(self, agent_id: str) -> None:
        """Removes an agent from registry.

        Args:
            agent_id: Unique agent ID.
        """
        with self._lock:
            if agent_id not in self._agents:
                raise AgentValidationError(f"Agent '{agent_id}' not found.")
            del self._agents[agent_id]

        self.logger.info(f"Agent unregistered. ID: {agent_id}")

    def get_agent(self, agent_id: str) -> BaseAgent:
        """Retrieves an agent from registry.

        Args:
            agent_id: Unique agent ID.

        Returns:
            BaseAgent: The agent.
        """
        with self._lock:
            if agent_id not in self._agents:
                raise AgentValidationError(f"Agent '{agent_id}' not found.")
            return self._agents[agent_id]

    def list_agents(self) -> List[BaseAgent]:
        """Lists registered agents.

        Returns:
            List[BaseAgent]: Active agents list.
        """
        with self._lock:
            return list(self._agents.values())

    def find_by_capability(self, capability: AgentCapability) -> List[BaseAgent]:
        """Finds all registered agents supporting capability.

        Args:
            capability: Target AgentCapability.

        Returns:
            List[BaseAgent]: Matching agents.
        """
        matched = []
        with self._lock:
            for agent in self._agents.values():
                # We match if capability.value or capability string matches agent capabilities list
                cap_str = capability.value
                if cap_str in agent.capabilities or capability in agent.capabilities:
                    matched.append(agent)
        return matched

    def health_check(self) -> Dict[str, str]:
        """Queries health status across registered agents.

        Returns:
            Dict[str, str]: Health status dictionary map.
        """
        status_map = {}
        with self._lock:
            for aid, agent in self._agents.items():
                status_map[aid] = agent.status.value
        return status_map


class AgentSelectionStrategy(ABC):
    """Interface defining agent selection filters."""

    @abstractmethod
    def select_agent(self, registry: AgentRegistry, capability: AgentCapability) -> BaseAgent:
        """Selects matching agent.

        Args:
            registry: Active registry.
            capability: Capability classification target.

        Returns:
            BaseAgent: Selected agent.
        """
        pass


class DefaultAgentSelectionStrategy(AgentSelectionStrategy):
    """Default strategy selecting healthy agent prioritizing Idle state."""

    def select_agent(self, registry: AgentRegistry, capability: AgentCapability) -> BaseAgent:
        candidates = registry.find_by_capability(capability)
        if not candidates:
            raise AgentValidationError(f"No registered agent supports capability: {capability.value}")

        # Uninitialized, healthy, and degraded status agents are all candidates
        healthy = [
            c for c in candidates
            if c.status in (AgentStatus.HEALTHY, AgentStatus.UNINITIALIZED, AgentStatus.DEGRADED)
        ]

        if not healthy:
            raise AgentValidationError(f"No healthy agent available for capability: {capability.value}")

        # Sort Idle or Uninitialized state first
        def score(a: BaseAgent) -> int:
            if a.state in (AgentState.IDLE, AgentState.UNINITIALIZED):
                return 0
            elif a.state == AgentState.BUSY:
                return 1
            return 2

        healthy.sort(key=score)
        return healthy[0]


class ResultAggregationStrategy(ABC):
    """Interface defining methods compiling results from multiple agents."""

    @abstractmethod
    def aggregate(self, results: Dict[str, Any]) -> Dict[str, Any]:
        """Aggregates execution output results.

        Args:
            results: Agent results dictionary.

        Returns:
            Dict[str, Any]: Compiled aggregated dictionary.
        """
        pass


class MergeAggregationStrategy(ResultAggregationStrategy):
    """Merges all outputs maps resolving duplicates prioritizing later executions."""

    def aggregate(self, results: Dict[str, Any]) -> Dict[str, Any]:
        merged = {}
        for aid, res in results.items():
            if isinstance(res, dict):
                merged.update(res)
            else:
                merged[aid] = res
        return merged


class OrchestratorAgent(BaseAgent):
    """Orchestrator coordinating execution maps across multiple specialized agents."""

    def __init__(
        self,
        name: str = "OrchestratorAgent",
        description: str = "Coordinates specialized agents execution",
        version: str = "1.0.0",
        capabilities: Optional[List[str]] = None
    ) -> None:
        caps = capabilities or ["ORCHESTRATION"]
        super().__init__(name=name, description=description, version=version, capabilities=caps)
        self.registry = AgentRegistry()
        self.event_bus = EventBus()
        self.selection_strategy: AgentSelectionStrategy = DefaultAgentSelectionStrategy()
        self.aggregation_strategy: ResultAggregationStrategy = MergeAggregationStrategy()
        self.logger = StructuredLogger()

    def initialize(self) -> None:
        """Initializes the orchestrator."""
        # Use simple try-block to ignore duplicates if already initialized by parent
        try:
            super().initialize()
        except Exception:
            pass

    def execute(self, task: Task) -> Any:
        # Implements BaseAgent execute signature
        # Convert task context to request
        req_id = str(uuid.uuid4())
        req = AgentRequest(
            request_id=req_id,
            user_id="task_system",
            input=task.description,
            context=task.metadata.copy()
        )
        res = self.handle(req)
        return res

    def handle(self, request: AgentRequest) -> AgentResponse:
        """Processes agent orchestration requests.

        Args:
            request: The request payload.

        Returns:
            AgentResponse: Consolidated outcomes.
        """
        if not request:
            raise AgentValidationError("AgentRequest cannot be None.")

        self.logger.info(f"Orchestrator request received. ID: {request.request_id}")
        self._publish_event("orchestrator.request.received", request_id=request.request_id)

        start_time = time.perf_counter()

        try:
            # Create execution plan
            plan = self.create_plan(request)
            self._publish_event("orchestrator.plan.created", request_id=request.request_id, plan_id=plan.plan_id)

            # Route & execute
            results = self.execute_plan(plan, request)

            # Aggregate
            aggregated = self.aggregate(results)

            duration = time.perf_counter() - start_time
            metrics = {
                "duration": duration,
                "agents_run_count": len(results)
            }

            self._publish_event("orchestrator.execution.completed", request_id=request.request_id)

            return AgentResponse(
                response_id=str(uuid.uuid4()),
                request_id=request.request_id,
                outputs=aggregated,
                execution_summary=f"Successfully orchestrated {len(results)} agents execution.",
                metrics=metrics,
                status="SUCCESS"
            )

        except Exception as e:
            duration = time.perf_counter() - start_time
            self.logger.error(f"Orchestration failure: {e}")
            metrics = {"duration": duration, "error": str(e)}

            return AgentResponse(
                response_id=str(uuid.uuid4()),
                request_id=request.request_id,
                outputs={},
                execution_summary=f"Orchestration failed: {e}",
                metrics=metrics,
                status="FAILURE"
            )

    def create_plan(self, request: AgentRequest) -> OrchestrationExecutionPlan:
        """Determines required capabilities and generates execution plan.

        Args:
            request: Target request query.

        Returns:
            OrchestrationExecutionPlan: Execution path.
        """
        input_text = request.input.lower()
        required_caps = []

        # Simple capability matcher heuristic matching keywords
        kw_map = {
            "chat": AgentCapability.CHAT,
            "ocr": AgentCapability.OCR,
            "search": AgentCapability.SEARCH,
            "embed": AgentCapability.EMBEDDING,
            "document": AgentCapability.DOCUMENT_PROCESSING,
            "code": AgentCapability.CODE_ANALYSIS,
            "resume": AgentCapability.RESUME_ANALYSIS,
            "meeting": AgentCapability.MEETING_ANALYSIS,
            "analytics": AgentCapability.ANALYTICS,
            "billing": AgentCapability.BILLING
        }

        for kw, cap in kw_map.items():
            if kw in input_text:
                required_caps.append(cap)

        if not required_caps:
            # Fallback default
            required_caps.append(AgentCapability.CHAT)

        participating = []
        dependencies = {}
        execution_order = []

        # Resolve selected agent ids mapping capabilities
        for cap in required_caps:
            agent = self.selection_strategy.select_agent(self.registry, cap)
            aid = str(agent.id)
            if aid not in participating:
                participating.append(aid)
                dependencies[aid] = []
                execution_order.append(aid)

        # Simple parallel groups configuration
        parallel_groups = [[aid] for aid in execution_order]

        return OrchestrationExecutionPlan(
            plan_id=str(uuid.uuid4()),
            participating_agents=participating,
            dependencies=dependencies,
            execution_order=execution_order,
            parallel_groups=parallel_groups,
            fallback_strategy=request.metadata.get("fallback_strategy", "abort")
        )

    def execute_plan(self, plan: OrchestrationExecutionPlan, request: AgentRequest) -> Dict[str, Any]:
        """Dispatches tasks in group topologies.

        Args:
            plan: The plan definition.
            request: The triggering request.

        Returns:
            Dict[str, Any]: Maps agent IDs to output results.
        """
        self._publish_event("orchestrator.execution.started", plan_id=plan.plan_id)
        results = {}

        for group in plan.parallel_groups:
            # Run parallel groups concurrently
            with concurrent.futures.ThreadPoolExecutor(max_workers=max(1, len(group))) as executor:
                future_to_agent = {}
                for aid in group:
                    agent = self.registry.get_agent(aid)
                    # Convert Request parameters into a Task
                    task = Task(
                        description=request.input,
                        metadata=request.context.copy()
                    )
                    # Validate agent is Idle
                    if agent.state == AgentState.UNINITIALIZED:
                        agent.initialize()

                    future = executor.submit(self._run_single_agent, agent, task, plan.fallback_strategy)
                    future_to_agent[future] = aid

                for future in concurrent.futures.as_completed(future_to_agent):
                    aid = future_to_agent[future]
                    try:
                        res = future.result()
                        results[aid] = res
                    except Exception as e:
                        self._publish_event("orchestrator.agent.failed", agent_id=aid, error=str(e))
                        if plan.fallback_strategy == "abort":
                            raise OrchestrationPlanError(f"Agent '{aid}' execution aborted: {e}") from e
                        elif plan.fallback_strategy == "retry":
                            # Simple single retry mechanism
                            self.logger.info(f"Retrying failed agent '{aid}' execution.")
                            try:
                                agent = self.registry.get_agent(aid)
                                # Reset error state to allow retry execution
                                agent.state = AgentState.IDLE
                                agent.status = AgentStatus.HEALTHY
                                task = Task(description=request.input, metadata=request.context.copy())
                                res = self._run_single_agent(agent, task, "abort")
                                results[aid] = res
                            except Exception as retry_err:
                                raise OrchestrationPlanError(f"Agent '{aid}' retry execution aborted: {retry_err}") from retry_err
                        else:
                            # ignore
                            results[aid] = {aid: {"status": "failed", "error": str(e)}}

        return results

    def _run_single_agent(self, agent: BaseAgent, task: Task, fallback_strategy: str) -> Any:
        agent.validate_task(task)
        agent.before_execute(task)
        try:
            res = agent.execute(task)
            return agent.after_execute(res)
        except Exception as e:
            agent.handle_error(e)
            raise

    def aggregate(self, results: Dict[str, Any]) -> Dict[str, Any]:
        """Invokes active ResultAggregationStrategy."""
        return self.aggregation_strategy.aggregate(results)

    def _publish_event(self, event_name: str, **kwargs: Any) -> None:
        event = Event(
            event_type=EventType.CUSTOM_EVENT,
            source="OrchestratorAgent",
            payload={"event_name": event_name, **kwargs}
        )
        self.event_bus.publish(event)
